build_mau:
  outputs:
    dev:
      account: LVB17920
      database: USER_DB_LION
      password: Sunny@22122003
      role: TRAINING_ROLE
      schema: analytics
      threads: 1
      type: snowflake
      user: LION
      warehouse: LION_QUERY_WH
  target: dev
